version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik
    networks:
      - poc-network
  
  api-service:
    build:
      context: ./api-service
      dockerfile: Dockerfile
    container_name: api-service
    restart: unless-stopped
    environment:
      - GIN_MODE=debug
      - PORT=8000
      - AUTH_SERVICE_URL=http://auth-service:8001
      - LOG_LEVEL=debug
    volumes:
      - ./api-service:/app
    networks:
      - poc-network
    depends_on:
      - auth-service
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.api.loadbalancer.server.port=8000"

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    restart: unless-stopped
    environment:
      - PORT=8001
      - MONGODB_URI=mongodb://mongodb:27017/auth
      - JWT_SECRET=your_jwt_secret_key_change_this_in_production
      - TOKEN_EXPIRY=24h
      - LOG_LEVEL=debug
    volumes:
      - ./auth-service:/app
    networks:
      - poc-network
    depends_on:
      - mongodb
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.auth.loadbalancer.server.port=8001"

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=auth
    volumes:
      - mongodb_data:/data/db
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - poc-network
    command: mongod --logpath=/dev/stdout
    ports:
      - "27017:27017"

  prometheus:
    image: prom/prometheus:v2.42.0
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - poc-network
    labels:
      - "traefik.enable=true"

networks:
  poc-network:
    driver: bridge

volumes:
  mongodb_data:
  prometheus_data:
