global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']

  - job_name: 'api-service'
    static_configs:
      - targets: ['api-service:8000']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8001']
